---
deployment:
  tasks:
    - export DEPLOYPATH=/home/nrogokum/backen
    - /bin/cp -R * $DEPLOYPATH
    - /bin/cp -R .env $DEPLOYPATH
    - /bin/cp -R .sequelizerc $DEPLOYPATH
    - /bin/cp -R .eslintignore $DEPLOYPATH
    - /bin/cp -R .eslintignore $DEPLOYPATH
